# services:
#   - type: web
#     name: django-app
#     env: python
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "gunicorn hello.wsgi:application"
#     migrationsCommand: "python manage.py migrate"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: your-database-name
#           property: connectionString

# databases:
#   - name: your-database-name
#     plan: free
#     region: oregon



services:
  - type: web
    name: bachatbaazar
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hello.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hello.settings
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: ashutoshpatil470@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Ashu@2602
    postDeploy:
      - python manage.py migrate
      - python manage.py createsuperuser --no-input \
          --username=$DJANGO_SUPERUSER_USERNAME \
          --email=$DJANGO_SUPERUSER_EMAIL \
          --password=$DJANGO_SUPERUSER_PASSWORD
