# Generated by Django 5.2.4 on 2025-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_age', models.CharField(max_length=100)),
                ('product_discription', models.TextField()),
                ('product_price', models.CharField(max_length=100)),
                ('product_file', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
