# Generated by Django 5.2.4 on 2025-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='contact',
            field=models.CharField(default='9999999999', max_length=15),
        ),
    ]
